Repository LuckyVicky-2team/backend, pull requests merged in 2024-10, with the labels that each got.

#255 Feat: 채팅 참여자 목록 조회 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/mapper/MeetingParticipantMapper.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingParticipantController.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingQueryFacadeImpl.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryUseCase.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingParticipantDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: feat

#258 Fix: 충돌 해결할 때 발생한 오류 해결
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryServiceV1.java
Labels: bug, fix

#260 Feat: 알림 목록 조회
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/mapper/NotificationMapper.java
  src/main/java/com/boardgo/domain/notification/controller/NotificationController.java
  src/main/java/com/boardgo/domain/notification/entity/MessageType.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationEntity.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationFail.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationMessage.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationMessageFormat.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationType.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationDslRepository.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/boardgo/domain/notification/repository/projection/NotificationProjection.java
  src/main/java/com/boardgo/domain/notification/service/NotificationQueryServiceV1.java
  src/main/java/com/boardgo/domain/notification/service/NotificationQueryUseCase.java
  src/main/java/com/boardgo/domain/notification/service/response/NotificationResponse.java
  src/main/java/com/boardgo/notification/entity/NotificationType.java
  src/test/java/com/boardgo/integration/data/NotificationData.java
  src/test/java/com/boardgo/integration/notification/controller/NotificationRestDocs.java
  src/test/java/com/boardgo/integration/notification/service/NotificationQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/termsconditions/controller/TermsConditionsRestDocs.java
Labels: feat

#263 Fix: 모임 수정 에러 해결
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/BoardGameProjection.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryUseCase.java
  src/main/java/com/boardgo/domain/boardgame/service/response/BoardGameByMeetingIdResponse.java
  src/main/java/com/boardgo/domain/boardgame/service/response/BoardGameResponse.java
  src/main/java/com/boardgo/domain/mapper/BoardGameMapper.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingCommandFacadeImpl.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingQueryFacadeImpl.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandFacadeImplTest.java
Labels: fix

#261 Feat: 알림 메세지 확인 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/notification/controller/NotificationController.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationEntity.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/boardgo/domain/notification/service/NotificationCommandServiceV1.java
  src/main/java/com/boardgo/domain/notification/service/NotificationCommandUseCase.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingLikeDocsTest.java
  src/test/java/com/boardgo/integration/notification/controller/NotificationRestDocs.java
  src/test/java/com/boardgo/integration/notification/service/NotificationCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/notification/NotificationEntityTest.java
Labels: feat

#268 Feat: 회원 푸시 토큰 저장 기능
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/user/controller/UserController.java
  src/main/java/com/boardgo/domain/user/controller/request/PushTokenRequest.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoStatus.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandUseCase.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
Labels: feat

#270 Fix: fcm key file 서브모듈 폴더 복사 로직 추가
  build.gradle
Labels: fix

#269 Feat: 모임 생성 시 채팅방도 같이 생성
  src/main/java/com/boardgo/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/boardgo/domain/chatting/service/ChatRoomCommandServiceV1.java
  src/main/java/com/boardgo/domain/chatting/service/ChatRoomCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandFacadeImplTest.java
Labels: feat

#271 Refactor: 리뷰 작성하기 퍼사드패턴 적용
  src/main/java/com/boardgo/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/boardgo/domain/chatting/service/ChatRoomCommandServiceV1.java
  src/main/java/com/boardgo/domain/chatting/service/ChatRoomCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingCommandFacadeImpl.java
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/service/ReviewCommandServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewCommandUseCase.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryUseCase.java
  src/main/java/com/boardgo/domain/review/service/facade/ReviewCommandFacade.java
  src/main/java/com/boardgo/domain/review/service/facade/ReviewCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandFacadeImplTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/review/facade/ReviewCommandFacadeTest.java
  src/test/java/com/boardgo/integration/review/service/ReviewQueryServiceV1Test.java
Labels: refectoring

#266 Fix: 모임 수정 오류 해결
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandFacadeImplTest.java
Labels: bug, fix

#274 Fix: 채팅방 목록 조회 시 모임 Id도 같이 반환
  src/main/java/com/boardgo/domain/chatting/service/response/ChattingListResponse.java
  src/main/java/com/boardgo/domain/mapper/ChatMapper.java
  src/test/java/com/boardgo/integration/chat/controller/ChatRoomDocsTest.java
Labels: fix

#272 Feat: 알림메세지 추가 기능 구현
  src/main/java/com/boardgo/domain/chatting/service/response/ChattingListResponse.java
  src/main/java/com/boardgo/domain/mapper/ChatMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingParticipantController.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingParticipantCommandFacade.java
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingParticipantCommandFacadeImpl.java
  src/main/java/com/boardgo/domain/notification/entity/MessageType.java
  src/main/java/com/boardgo/domain/notification/entity/NotificationMessageFormat.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationMessageFormatRepository.java
  src/main/java/com/boardgo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/boardgo/domain/notification/service/NotificationCommandServiceV1.java
  src/main/java/com/boardgo/domain/notification/service/NotificationCommandUseCase.java
  src/main/java/com/boardgo/domain/notification/service/NotificationMessageFactory.java
  src/main/java/com/boardgo/domain/notification/service/request/NotificationCreateRequest.java
  src/main/java/com/boardgo/init/NotificationMessageFormatInitializer.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/integration/chat/controller/ChatRoomDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/notification/service/NotificationCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/user/controller/PersonalInfoDocsTest.java
  src/test/java/com/boardgo/unittest/user/MessageTypeTest.java
Labels: feat

#277 Feat: 알림설정 도메인 엔티티 설계
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/notification/entity/NotificationSettingEntity.java
  src/main/java/com/boardgo/domain/notification/entity/UserNotificationSettingEntity.java
  src/main/java/com/boardgo/domain/termsconditions/controller/UserTermsConditionsController.java
  src/main/java/com/boardgo/domain/termsconditions/entity/TermsConditionsEntity.java
  src/main/java/com/boardgo/domain/termsconditions/service/TermsConditionsFactory.java
  src/main/java/com/boardgo/domain/termsconditions/service/facade/UserTermsConditionsCommandFacadeImpl.java
  src/main/java/com/boardgo/init/TermsConditionsInitializer.java
  src/test/java/com/boardgo/integration/termsconditions/controller/TermsConditionsRestDocs.java
  src/test/java/com/boardgo/integration/termsconditions/controller/UserTermsConditionsRestDocs.java
  src/test/java/com/boardgo/integration/termsconditions/facade/UserTermsConditionsCommandFacadeTest.java
Labels: refectoring, feat

#279 Fix: 채팅 목록 조회 로직 수정
  src/main/java/com/boardgo/domain/chatting/service/ChatMessageQueryServiceV1.java
  src/main/java/com/boardgo/domain/chatting/service/facade/ChatRoomQueryFacadeImpl.java
  src/main/java/com/boardgo/domain/mapper/ChatMapper.java
Labels: bug, fix

#281 Feat: 회원 알림설정 항목 저장
  src/main/java/com/boardgo/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/com/boardgo/domain/notification/repository/UserNotificationSettingRepository.java
  src/main/java/com/boardgo/domain/notification/service/UserNotificationSettingCommandServiceV1.java
  src/main/java/com/boardgo/domain/notification/service/UserNotificationSettingCommandUseCase.java
  src/main/java/com/boardgo/domain/termsconditions/service/facade/UserTermsConditionsCommandFacadeImpl.java
  src/test/java/com/boardgo/config/NotificationCommandFacadeTestConfig.java
  src/test/java/com/boardgo/config/UserNotificationSettingCommandUseCaseTestConfig.java
  src/test/java/com/boardgo/integration/notification/service/UserNotificationSettingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/termsconditions/facade/UserTermsConditionsCommandFacadeTest.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
  src/test/java/com/boardgo/integration/user/facade/UserCommandFacadeTest.java
Labels: feat
