Repository LuckyVicky-2team/backend, pull requests merged in 2024-08, with the labels that each got.

#14 Feat: spotless 코드 포멧팅 및 pre-commit spotless 적용
  .github/workflows/dev-ci.yml
  build.gradle
  script/pre-commit
  src/main/java/com/boardgo/BoardgoApplication.java
Labels: feat

#18 Feat: 회원가입 기능 구현
  build.gradle
  src/main/java/com/boardgo/common/config/SecurityConfig.java
  src/main/java/com/boardgo/common/constant/HeaderConstant.java
  src/main/java/com/boardgo/common/validator/ListInStringNotEmptyValidator.java
  src/main/java/com/boardgo/common/validator/annotation/ListInStringNotEmpty.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/mapper/UserPrTagMapper.java
  src/main/java/com/boardgo/domain/user/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/controller/SignupControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/dto/SignupRequest.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/entity/UserPrTagEntity.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserRepository.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserUseCase.java
  src/test/java/com/boardgo/integration/support/IntegrationTestSupport.java
  src/test/java/com/boardgo/integration/support/RestDocsTestSupport.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
  src/test/java/com/boardgo/unittest/user/fake/FakePasswordEncoder.java
  src/test/resources/application.yml
  typescript
Labels: feat

#22 Fix: gradle 빌드 이슈- spotless gradle 설정 수정
  build.gradle
  src/main/java/com/boardgo/common/config/SecurityConfig.java
  src/main/java/com/boardgo/common/constant/HeaderConstant.java
  src/main/java/com/boardgo/common/domain/BaseEntity.java
  src/main/java/com/boardgo/common/exception/advice/CommonControllerAdvice.java
  src/main/java/com/boardgo/common/exception/advice/dto/ErrorResponse.java
  src/main/java/com/boardgo/common/exception/advice/dto/FieldErrorResponse.java
  src/main/java/com/boardgo/common/validator/ListInStringNotEmptyValidator.java
  src/main/java/com/boardgo/common/validator/annotation/ListInStringNotEmpty.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/mapper/UserPrTagMapper.java
  src/main/java/com/boardgo/domain/user/controller/SignupControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/dto/SignupRequest.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/entity/UserPrTagEntity.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserRepository.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserUseCase.java
  src/test/java/com/boardgo/BoardgoApplicationTests.java
  src/test/java/com/boardgo/integration/support/IntegrationTestSupport.java
  src/test/java/com/boardgo/integration/support/RestDocsTestSupport.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
  src/test/java/com/boardgo/unittest/user/fake/FakePasswordEncoder.java
Labels: bug

#20 Feat: 로깅 인터셉터 구현 및 로그백 설정
  src/main/java/com/boardgo/config/WebConfig.java
  src/main/java/com/boardgo/config/filter/CommonRequestWrapper.java
  src/main/java/com/boardgo/config/filter/LoggingFilter.java
  src/main/java/com/boardgo/config/interceptor/LoggingInterceptor.java
  src/main/java/com/boardgo/config/log/LoggingMessage.java
  src/main/java/com/boardgo/config/log/OutputLog.java
  src/main/resources/console-appender.xml
  src/main/resources/error-logging-appender.xml
  src/main/resources/info-logging-appender.xml
  src/main/resources/logback-spring.xml
Labels: feat

#27 Feat: UserEntity 필드 ProviderType 타입 추가
  src/main/java/com/boardgo/domain/oauth2/entity/ProviderType.java
  src/main/java/com/boardgo/domain/user/controller/dto/SignupRequest.java
  src/main/java/com/boardgo/domain/user/entity/RoleType.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
Labels: feat

#13 Feat: 레이어드 계층 컨벤션, 네이밍 컨벤션 테스트 코드 작성
  src/main/java/com/boardgo/common/exception/advice/dto/ErrorCode.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepositoryImpl.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/convention/NamingConventionTest.java
Labels: feat

#41 Fix: rest docs
  .github/workflows/dev-cd.yml
  build.gradle
Labels: bug

#43 Fix: RestDocs 문서화 버그 수정
  .github/workflows/dev-cd.yml
  build.gradle
Labels: bug

#48 Fix: Request 데이터 캐싱처리 filter 예외수정
  src/main/java/com/boardgo/common/constant/TimeConstant.java
  src/main/java/com/boardgo/common/exception/advice/CommonControllerAdvice.java
  src/main/java/com/boardgo/config/WebConfig.java
  src/main/java/com/boardgo/config/filter/CommonRequestWrapper.java
  src/main/java/com/boardgo/config/filter/LoggingFilter.java
  src/main/java/com/boardgo/config/interceptor/LoggingInterceptor.java
  src/main/java/com/boardgo/config/log/LoggingMessage.java
Labels: bug

#56 Fix: 회원 권한 인증 수정 및 커스텀 예외 추가
  src/main/java/com/boardgo/common/controller/HealthCheckController.java
  src/main/java/com/boardgo/common/exception/CookieNotFoundException.java
  src/main/java/com/boardgo/common/exception/CustomNullPointException.java
  src/main/java/com/boardgo/common/exception/OAuth2Exception.java
  src/main/java/com/boardgo/common/exception/advice/CommonControllerAdvice.java
  src/main/java/com/boardgo/common/exception/advice/dto/ErrorCode.java
  src/main/java/com/boardgo/common/utils/CookieUtils.java
  src/main/java/com/boardgo/common/utils/SecurityUtils.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/config/WebConfig.java
  src/main/java/com/boardgo/config/interceptor/LoggingInterceptor.java
  src/main/java/com/boardgo/domain/user/controller/TokenControllerV1.java
  src/main/java/com/boardgo/domain/user/entity/RoleType.java
  src/main/java/com/boardgo/domain/user/service/dto/CustomUserDetails.java
  src/main/java/com/boardgo/oauth2/dto/OAuth2UserResponseFactory.java
  src/main/java/com/boardgo/oauth2/entity/CustomOAuth2User.java
  src/main/java/com/boardgo/oauth2/handler/OAuth2SuccessHandler.java
Labels: bug

#57 Feat: 소셜로그인 회원가입 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/domain/BaseEntity.java
  src/main/java/com/boardgo/common/utils/StringUtils.java
  src/main/java/com/boardgo/common/utils/ValidateUtils.java
  src/main/java/com/boardgo/domain/user/controller/SignupControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/dto/SocialSignupRequest.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/service/UserCommandCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandUseCase.java
  src/main/resources/console-appender.xml
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/validation/ListInStringNotEmptyValidatorTest.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
  src/test/java/com/boardgo/unittest/utils/StringUtilsTest.java
  src/test/java/com/boardgo/unittest/utils/ValidateUtilsTest.java
Labels: enhancement, feat

#58 Feat: personal info 개인정보 조회
  script/start.sh
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/exception/CustomNullPointException.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/config/WebConfig.java
  src/main/java/com/boardgo/config/filter/LoggingFilter.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/user/controller/UserControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/dto/UserPersonalInfoResponse.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/service/UserCommandCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryUseCase.java
  src/main/java/com/boardgo/init/BoardGameInitializer.java
  src/test/java/com/boardgo/integration/support/RestDocsTestSupport.java
  src/test/java/com/boardgo/integration/user/controller/TokenDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: bug, feat

#59 Feat: 모임 목록 조회 기능 구현
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/utils/S3Service.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/config/WebConfig.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/controller/request/MeetingCreateRequest.java
  src/main/java/com/boardgo/domain/meeting/controller/request/MeetingSearchRequest.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantSubEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingGameMatchRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingGenreMatchRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingSearchResponse.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryUseCase.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/init/BoardGameInitializer.java
  src/main/java/com/boardgo/init/MeetingInitializer.java
  src/main/java/com/boardgo/init/UserInfoInitializer.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
  src/test/java/com/boardgo/unittest/utils/S3ServiceTest.java
Labels: feat

#62 Feat: 크롤링한 데이터 보드게임 추가 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/controller/request/BoardGameCreateListRequest.java
  src/main/java/com/boardgo/domain/boardgame/controller/request/BoardGameCreateRequest.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameGenreJdbcRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameGenreJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameGenreRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameJdbcRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/GameGenreMatchJdbcRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/GameGenreMatchJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/GameGenreMatchRepository.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandUseCase.java
  src/main/java/com/boardgo/domain/mapper/BoardGameMapper.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/init/BoardGameInitializer.java
  src/main/java/com/boardgo/init/MeetingInitializer.java
  src/main/java/com/boardgo/init/UserInfoInitializer.java
  src/test/java/com/boardgo/integration/boardgame/controller/BoardGameDocsTest.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/support/IntegrationTestSupport.java
  src/test/java/com/boardgo/integration/support/RestDocsTestSupport.java
  src/test/java/com/boardgo/unittest/boardgame/BoardGameEntityTest.java
Labels: feat

#65 Feat: 개인정보 수정, PR 태그 수정, 프로필 수정 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/constant/S3BucketConstant.java
  src/main/java/com/boardgo/common/exception/CustomS3Exception.java
  src/main/java/com/boardgo/common/exception/OAuth2Exception.java
  src/main/java/com/boardgo/common/exception/advice/CommonControllerAdvice.java
  src/main/java/com/boardgo/common/exception/advice/dto/ErrorCode.java
  src/main/java/com/boardgo/common/utils/CustomStringUtils.java
  src/main/java/com/boardgo/common/utils/S3Service.java
  src/main/java/com/boardgo/common/utils/StringUtils.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/controller/PersonalInfoController.java
  src/main/java/com/boardgo/domain/user/controller/UserControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/dto/UserPersonalInfoUpdateRequest.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/repository/UserPrTagJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandUseCase.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/jwt/JWTFilter.java
  src/test/java/com/boardgo/integration/fixture/UserInfoFixture.java
  src/test/java/com/boardgo/integration/fixture/UserPrTagFixture.java
  src/test/java/com/boardgo/integration/user/controller/PersonalInfoDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/utils/StringUtilsTest.java
Labels: feat

#70 Feat: 보드게임 검색 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/controller/request/BoardGameSearchRequest.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/BoardGameSearchProjection.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/GenreSearchProjection.java
  src/main/java/com/boardgo/domain/boardgame/repository/response/BoardGameSearchResponse.java
  src/main/java/com/boardgo/domain/boardgame/repository/response/GenreSearchResponse.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryUseCase.java
  src/main/java/com/boardgo/domain/mapper/BoardGameGenreMapper.java
  src/main/java/com/boardgo/domain/mapper/BoardGameMapper.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/integration/boardgame/controller/BoardGameDocsTest.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/fixture/UserInfoFixture.java
  src/test/java/com/boardgo/integration/fixture/UserPrTagFixture.java
  src/test/java/com/boardgo/integration/init/TestBoardGameInitializer.java
  src/test/java/com/boardgo/integration/init/TestMeetingInitializer.java
  src/test/java/com/boardgo/integration/init/TestUserInfoInitializer.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
Labels: feat

#72 Fix: 모임 목록 조회 기능에서 누락된 정보인 썸네일 추가
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingSearchResponse.java
  src/test/java/com/boardgo/integration/boardgame/controller/BoardGameDocsTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
Labels: fix

#74 Feat: 개인정보 수정 테스트코드 작성
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/test/java/com/boardgo/integration/fixture/UserInfoFixture.java
  src/test/java/com/boardgo/integration/fixture/UserPrTagFixture.java
  src/test/java/com/boardgo/integration/user/controller/PersonalInfoDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
Labels: feat

#76 Fix: 폴더명 변경
  .ebextensions/00-makeFiles.config
Labels: fix

#81 Feat: 모임 상세 조회 기능 구현
  .github/workflows/prod-cd.yml
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/BoardGameByMeetingIdProjection.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/BoardGameSearchProjection.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/GenreSearchProjection.java
  src/main/java/com/boardgo/domain/boardgame/repository/response/BoardGameByMeetingIdResponse.java
  src/main/java/com/boardgo/domain/boardgame/repository/response/BoardGameListResponse.java
  src/main/java/com/boardgo/domain/mapper/BoardGameMapper.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingDetailProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCreateFactory.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCreateFactoryV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryUseCase.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/repository/UserRepository.java
  src/main/java/com/boardgo/domain/user/repository/projection/UserParticipantProjection.java
  src/main/java/com/boardgo/domain/user/repository/response/UserParticipantResponse.java
  src/main/java/com/boardgo/init/MeetingInitializer.java
  src/test/java/com/boardgo/integration/init/TestMeetingInitializer.java
  src/test/java/com/boardgo/integration/init/TestUserInfoInitializer.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
Labels: feat

#86 Feat: 워크 플로 수정
  .github/workflows/prod-cd.yml
Labels: bug, feat

#88 Fix: nginx 경로 수정 (#87)
  .platform/nginx/nginx.conf
Labels: bug

#97 Fix: 모임 개설 시 정보 추가
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/request/MeetingCreateRequest.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/init/MeetingInitializer.java
  src/test/java/com/boardgo/integration/init/TestMeetingInitializer.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
Labels: feat

#98 Fix: 엔티티 컬럼 추가로 인한 오류 수정
  src/test/java/com/boardgo/integration/fixture/MeetingFixture.java
Labels: bug

#106 Fix: 배포 브랜치 워크 플로 수정
  .github/workflows/prod-cd.yml
Labels: fix

#139 Feat: 평가태그 목록 조회 기능구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/mapper/EvaluationTagMapper.java
  src/main/java/com/boardgo/domain/review/controller/EvaluationTagController.java
  src/main/java/com/boardgo/domain/review/controller/dto/EvaluationTagListResponse.java
  src/main/java/com/boardgo/domain/review/controller/dto/EvaluationTagResponse.java
  src/main/java/com/boardgo/domain/review/entity/EvaluationTagEntity.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagRepository.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagUseCase.java
  src/test/java/com/boardgo/integration/fixture/EvaluationTagFixture.java
  src/test/java/com/boardgo/integration/review/controller/EvaluationTagDocs.java
  src/test/java/com/boardgo/integration/review/service/EvaluationTagQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: feat

#141 Feat: 평가태그 목록 조회 기능구현 (#139)
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/mapper/EvaluationTagMapper.java
  src/main/java/com/boardgo/domain/review/controller/EvaluationTagController.java
  src/main/java/com/boardgo/domain/review/controller/dto/EvaluationTagListResponse.java
  src/main/java/com/boardgo/domain/review/controller/dto/EvaluationTagResponse.java
  src/main/java/com/boardgo/domain/review/entity/EvaluationTagEntity.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagRepository.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagUseCase.java
  src/test/java/com/boardgo/integration/fixture/EvaluationTagFixture.java
  src/test/java/com/boardgo/integration/review/controller/EvaluationTagDocs.java
  src/test/java/com/boardgo/integration/review/service/EvaluationTagQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: feat

#142 Fix: 모임 목록과 상세에 찜 여부 추가
  src/main/java/com/boardgo/common/utils/SecurityUtils.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingLike.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingSearchResponse.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
Labels: feat, fix

#143 Fix: 보드게임 생성 API 되지 않는 오류 수정
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/controller/request/BoardGameCreateRequest.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/test/java/com/boardgo/integration/boardgame/controller/BoardGameDocsTest.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/boardgame/BoardGameEntityTest.java
Labels: fix

#144 Feat: 모임 찜하기 기능 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/exception/CustomNoSuchElementException.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/mapper/MeetingLikeMapper.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingLikeController.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingLikeEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeJdbcRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingDetailProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingSearchResponse.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingLikeCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingLikeCommandUseCase.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingLikeDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingLikeCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingLikeEntityTest.java
Labels: feat

#154 Fix: Prod 충돌 해결
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/exception/CustomNoSuchElementException.java
  src/main/java/com/boardgo/common/utils/SecurityUtils.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/controller/request/BoardGameCreateRequest.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameCommandUseCase.java
  src/main/java/com/boardgo/domain/mapper/MeetingLikeMapper.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingLikeController.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingLikeEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeJdbcRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeJdbcRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingDetailProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingSearchProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingSearchResponse.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingLikeCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingLikeCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/test/java/com/boardgo/integration/boardgame/controller/BoardGameDocsTest.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingLikeDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingLikeCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/boardgame/BoardGameEntityTest.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
  src/test/java/com/boardgo/unittest/meeting/MeetingLikeEntityTest.java
Labels: feat

#160 Fix: 개인정보 수정 API 비밀번호 변경이슈 처리
  src/main/java/com/boardgo/common/exception/DuplicateException.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
Labels: bug

#170 Feat: 찜한 목록 조회 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MyPageMeetingController.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingLikeEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/LikedMeetingMyPageProjection.java
  src/main/java/com/boardgo/domain/meeting/service/MyPageMeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MyPageMeetingQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/response/LikedMeetingMyPageResponse.java
  src/test/java/com/boardgo/integration/fixture/MeetingLikeFixture.java
  src/test/java/com/boardgo/integration/meeting/controller/MyPageMeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MyPageMeetingQueryServiceV1Test.java
Labels: feat

#178 Feat: 리뷰 모임 목록 조회 및 리뷰 작성하기 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/utils/CustomStringUtils.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/boardgame/entity/SituationType.java
  src/main/java/com/boardgo/domain/mapper/EvaluationTagMapper.java
  src/main/java/com/boardgo/domain/mapper/ReviewMapper.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingReviewProjection.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/ParticipationCountProjection.java
  src/main/java/com/boardgo/domain/review/controller/EvaluationTagController.java
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/controller/request/ReviewCreateRequest.java
  src/main/java/com/boardgo/domain/review/entity/ReviewEntity.java
  src/main/java/com/boardgo/domain/review/entity/enums/ReviewType.java
  src/main/java/com/boardgo/domain/review/repository/ReviewRepository.java
  src/main/java/com/boardgo/domain/review/repository/projection/ReviewCountProjection.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/EvaluationTagUseCase.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewUseCase.java
  src/main/java/com/boardgo/domain/review/service/response/EvaluationTagListResponse.java
  src/main/java/com/boardgo/domain/review/service/response/EvaluationTagResponse.java
  src/main/java/com/boardgo/domain/review/service/response/ReviewMeetingResponse.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/test/java/com/boardgo/integration/review/controller/ReviewRestDocs.java
  src/test/java/com/boardgo/integration/review/service/EvaluationTagQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/review/service/ReviewQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/support/RestDocsTestSupport.java
Labels: feat

#183 Fix: 누적 인기 보드게임 빈배열일 경우 HTTP 메소드 코드 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/boardgame/controller/HomeBoardGameController.java
Labels: fix

#182 Feat: 방장이 내보낸 사람인지 확인 API
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/meeting/controller/MeetingParticipantController.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/response/ParticipantOutResponse.java
  src/test/java/com/boardgo/integration/fixture/MeetingParticipantFixture.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingParticipantDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantQueryServiceV1Test.java
Labels: feat

#186 Feat: 작성할 리뷰 참여자 목록 조회하기
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/exception/advice/CommonControllerAdvice.java
  src/main/java/com/boardgo/domain/mapper/ReviewMapper.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/ReviewMeetingParticipantsProjection.java
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/repository/ReviewRepository.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewUseCase.java
  src/main/java/com/boardgo/domain/review/service/response/ReviewMeetingParticipantsResponse.java
  src/main/java/com/boardgo/domain/user/controller/PersonalInfoController.java
  src/test/java/com/boardgo/integration/review/controller/ReviewRestDocs.java
Labels: feat

#205 Feat: 내 리뷰 조회하기
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagDslRepository.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagRepository.java
  src/main/java/com/boardgo/domain/review/repository/ReviewDslRepository.java
  src/main/java/com/boardgo/domain/review/repository/ReviewDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/review/repository/projection/MyEvaluationTagProjection.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewUseCase.java
  src/main/java/com/boardgo/domain/review/service/response/MyEvaluationTagResponse.java
  src/main/java/com/boardgo/domain/review/service/response/MyReviewsResponse.java
  src/test/java/com/boardgo/integration/review/controller/ReviewRestDocs.java
Labels: feat

#204 Fix: 모임 상세 - 모임 작성자 정보 추가
  .ebextensions/01-setup-timezone.config
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
Labels: fix

#207 Feat: boardgo v.1.2
  .ebextensions/01-setup-timezone.config
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagDslRepository.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/review/repository/EvaluationTagRepository.java
  src/main/java/com/boardgo/domain/review/repository/ReviewDslRepository.java
  src/main/java/com/boardgo/domain/review/repository/ReviewDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/review/repository/projection/MyEvaluationTagProjection.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewUseCase.java
  src/main/java/com/boardgo/domain/review/service/response/MyEvaluationTagResponse.java
  src/main/java/com/boardgo/domain/review/service/response/MyReviewsResponse.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/review/controller/ReviewRestDocs.java
Labels: version

#209 Hotfix: 상황별 보드게임 최소/최대인원 추가
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/repository/projection/SituationBoardGameProjection.java
  src/main/java/com/boardgo/domain/boardgame/service/response/SituationBoardGameResponse.java
  src/test/java/com/boardgo/integration/boardgame/controller/HomeBoardGameDocsTest.java
Labels: fix

#211 Fix: 보드게임 검색 query 수정 ..!
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameQueryServiceV1Test.java
Labels: fix
