Repository LuckyVicky-2team/backend, pull requests merged in 2024-09, with the labels that each got.

#216 Fix: 유니크 제약조건 설정 및 모임 상세조회 버그 수정
  src/main/java/com/boardgo/domain/boardgame/entity/BoardGameEntity.java
  src/main/java/com/boardgo/domain/boardgame/entity/GameGenreMatchEntity.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingGameMatchEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingGenreMatchEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/MeetingDetailProjection.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
Labels: fix

#215 Feat: 날짜 지난 모임 [모임 종료] 상태 변경 기능 구현
  build.gradle
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingBatchServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/main/java/com/boardgo/schedule/config/AutowiringSpringBeanJobFactory.java
  src/main/java/com/boardgo/schedule/config/JobsListener.java
  src/main/java/com/boardgo/schedule/config/QuartzConfig.java
  src/main/java/com/boardgo/schedule/config/TriggersListener.java
  src/main/java/com/boardgo/schedule/job/FinishedMeetingStateJob.java
  src/main/java/com/boardgo/schedule/service/FinishedMeetingStateService.java
  src/main/java/com/boardgo/schedule/service/TriggerService.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/integration/data/MeetingData.java
  src/test/java/com/boardgo/integration/data/UserInfoData.java
  src/test/java/com/boardgo/integration/fixture/MeetingFixture.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingBatchServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
Labels: bug, feat

#219 Feat: 모임 모집완료 상태변경 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantSubEntity.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantCommandServiceV1.java
  src/main/java/com/boardgo/schedule/service/FinishedMeetingStateService.java
  src/main/java/com/boardgo/schedule/service/JobDetailService.java
  src/main/java/com/boardgo/schedule/service/TriggerService.java
  src/main/java/com/boardgo/schedule/service/enums/JobGroups.java
  src/main/java/com/boardgo/schedule/service/enums/ScheduleJobs.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingBatchServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
Labels: feat

#220 Refactor: user 도메인 dto 패키지 변경 및 파일명 변명
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/utils/SecurityUtils.java
  src/main/java/com/boardgo/config/interceptor/LoggingInterceptor.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/user/controller/PersonalInfoController.java
  src/main/java/com/boardgo/domain/user/controller/SignupControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/UserControllerV1.java
  src/main/java/com/boardgo/domain/user/controller/request/EmailRequest.java
  src/main/java/com/boardgo/domain/user/controller/request/NickNameRequest.java
  src/main/java/com/boardgo/domain/user/controller/request/SignupRequest.java
  src/main/java/com/boardgo/domain/user/controller/request/SocialSignupRequest.java
  src/main/java/com/boardgo/domain/user/controller/request/UserPersonalInfoUpdateRequest.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/user/repository/projection/PersonalInfoProjection.java
  src/main/java/com/boardgo/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandUseCase.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryUseCase.java
  src/main/java/com/boardgo/domain/user/service/response/CustomUserDetails.java
  src/main/java/com/boardgo/domain/user/service/response/OtherPersonalInfoResponse.java
  src/main/java/com/boardgo/domain/user/service/response/UserPersonalInfoResponse.java
  src/main/java/com/boardgo/jwt/JWTFilter.java
  src/main/java/com/boardgo/jwt/LoginFilter.java
  src/test/java/com/boardgo/convention/NamingConventionTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingLikeDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingLikeCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MyPageMeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/controller/PersonalInfoDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/validation/ListInStringNotEmptyValidatorTest.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
Labels: refectoring

#222 Refactor: 모임 테스트 데이터 코드 data builder pattern 으로 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/init/BoardGameInitializer.java
  src/main/java/com/boardgo/init/MeetingInitializer.java
  src/main/java/com/boardgo/init/UserInfoInitializer.java
  src/test/java/com/boardgo/integration/fixture/MeetingFixture.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingParticipantDocsTest.java
  src/test/java/com/boardgo/integration/meeting/controller/MyPageMeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MyPageMeetingQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingEntityTest.java
Labels: refectoring

#224 Feat: 모임 삭제 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantSubEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingGameMatchRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingGenreMatchRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingLikeRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipateWaitingRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingParticipantSubEntityTest.java
Labels: feat

#226 Refactor: Repository/response -> Service/response 변경
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepository.java
  src/main/java/com/boardgo/domain/boardgame/repository/BoardGameDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryServiceV1.java
  src/main/java/com/boardgo/domain/boardgame/service/BoardGameQueryUseCase.java
  src/main/java/com/boardgo/domain/boardgame/service/response/BoardGameListResponse.java
  src/main/java/com/boardgo/domain/boardgame/service/response/BoardGameSearchResponse.java
  src/main/java/com/boardgo/domain/boardgame/service/response/GenreSearchResponse.java
  src/main/java/com/boardgo/domain/mapper/BoardGameGenreMapper.java
  src/main/java/com/boardgo/domain/mapper/BoardGameMapper.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/response/BoardGameByMeetingIdResponse.java
  src/main/java/com/boardgo/domain/meeting/service/response/MeetingDetailResponse.java
  src/main/java/com/boardgo/domain/meeting/service/response/MeetingSearchResponse.java
  src/main/java/com/boardgo/domain/meeting/service/response/UserParticipantResponse.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepository.java
  src/main/java/com/boardgo/domain/user/repository/UserDslRepositoryImpl.java
  src/test/java/com/boardgo/integration/boardgame/service/BoardGameQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
Labels: refectoring

#227 Feat: 모임 종료 3시간 후부터 리뷰 작성 가능 추가
  src/main/java/com/boardgo/common/constant/TimeConstant.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/review/controller/ReviewController.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryUseCase.java
  src/test/java/com/boardgo/integration/data/UserInfoData.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/review/controller/ReviewRestDocs.java
  src/test/java/com/boardgo/integration/review/service/ReviewQueryServiceV1Test.java
  src/test/java/com/boardgo/unittest/meeting/MeetingParticipantSubEntityTest.java
Labels: feat

#228 Feat: 모임 수정하기 기능 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/meeting/controller/MeetingController.java
  src/main/java/com/boardgo/domain/meeting/controller/request/MeetingUpdateRequest.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingEntity.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCommandUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCreateFactory.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingCreateFactoryV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCreateFactoryTest.java
Labels: feat

#229 Feat: 다른 사람 프로필 조회 시 평가태그 추가
  src/main/java/com/boardgo/domain/mapper/UserInfoMapper.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantQueryUseCase.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryUseCase.java
  src/main/java/com/boardgo/domain/review/service/response/MyEvaluationTagsResponse.java
  src/main/java/com/boardgo/domain/user/controller/PersonalInfoController.java
  src/main/java/com/boardgo/domain/user/controller/SignupController.java
  src/main/java/com/boardgo/domain/user/controller/TokenController.java
  src/main/java/com/boardgo/domain/user/controller/UserController.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryUseCase.java
  src/main/java/com/boardgo/domain/user/service/facade/UserQueryServiceFacade.java
  src/main/java/com/boardgo/domain/user/service/facade/UserQueryServiceFacadeImpl.java
  src/main/java/com/boardgo/domain/user/service/response/OtherPersonalInfoResponse.java
  src/main/java/com/boardgo/domain/user/service/response/UserInfoResponse.java
  src/test/java/com/boardgo/convention/LayeredDependencyConventionTest.java
  src/test/java/com/boardgo/integration/review/service/ReviewQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/controller/PersonalInfoDocsTest.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: feat

#230 Feat: 모임 나가기, 내보내기 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/validator/EnumValidator.java
  src/main/java/com/boardgo/common/validator/annotation/EnumValue.java
  src/main/java/com/boardgo/domain/meeting/controller/MeetingParticipantController.java
  src/main/java/com/boardgo/domain/meeting/controller/request/MeetingOutRequest.java
  src/main/java/com/boardgo/domain/meeting/entity/MeetingParticipantEntity.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingParticipantRepository.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantCommandServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingParticipantCommandUseCase.java
  src/test/java/com/boardgo/integration/meeting/controller/MeetingParticipantDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingParticipantCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/validation/EnumValidatorTest.java
  src/test/java/com/boardgo/unittest/meeting/MeetingParticipantEntityTest.java
Labels: feat

#231 Feat: 약관동의 엔티티 및 테이블 설계
  src/main/java/com/boardgo/domain/meeting/entity/MeetingLikeEntity.java
  src/main/java/com/boardgo/domain/termsconditions/entity/TermsConditionsEntity.java
  src/main/java/com/boardgo/domain/termsconditions/entity/TermsConditionsHistoryEntity.java
  src/main/java/com/boardgo/domain/termsconditions/entity/UserTermsConditionsEntity.java
  src/main/java/com/boardgo/domain/termsconditions/entity/enums/TermsConditionsType.java
  src/main/java/com/boardgo/domain/termsconditions/repository/TermsConditionsRepository.java
  src/main/java/com/boardgo/domain/termsconditions/repository/UserTermsConditionsRepository.java
Labels: feat

#233 Feat: 메인 홈 마감임박 모임
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/boardgame/controller/BoardGameController.java
  src/main/java/com/boardgo/domain/boardgame/service/HomeBoardGameQueryUseCase.java
  src/main/java/com/boardgo/domain/mapper/MeetingMapper.java
  src/main/java/com/boardgo/domain/meeting/controller/HomeMeetingController.java
  src/main/java/com/boardgo/domain/meeting/entity/enums/MeetingSortType.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepository.java
  src/main/java/com/boardgo/domain/meeting/repository/MeetingDslRepositoryImpl.java
  src/main/java/com/boardgo/domain/meeting/repository/projection/HomeMeetingDeadlineProjection.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingBatchService.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryServiceV1.java
  src/main/java/com/boardgo/domain/meeting/service/MeetingQueryUseCase.java
  src/main/java/com/boardgo/domain/meeting/service/response/HomeMeetingDeadlineResponse.java
  src/main/java/com/boardgo/schedule/job/FinishedMeetingStateJob.java
  src/test/java/com/boardgo/integration/meeting/controller/HomeMeetingDocsTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingBatchServiceTest.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingQueryServiceV1Test.java
Labels: feat

#238 Feat: 리프레시 토큰 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/common/constant/TimeConstant.java
  src/main/java/com/boardgo/common/exception/CustomNullPointException.java
  src/main/java/com/boardgo/common/utils/CookieUtils.java
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/jwt/JWTUtil.java
  src/main/java/com/boardgo/jwt/LoginFilter.java
  src/main/java/com/boardgo/jwt/controller/AuthController.java
  src/main/java/com/boardgo/jwt/entity/AuthEntity.java
  src/main/java/com/boardgo/jwt/repository/AuthRepository.java
  src/main/java/com/boardgo/jwt/service/LoginService.java
  src/main/java/com/boardgo/jwt/service/TokenService.java
  src/main/java/com/boardgo/jwt/service/facade/AuthFacade.java
  src/main/java/com/boardgo/oauth2/handler/OAuth2SuccessHandler.java
  src/test/java/com/boardgo/integration/jwt/controller/AuthDocsTest.java
  src/test/java/com/boardgo/integration/jwt/service/AuthFacadeTest.java
  src/test/java/com/boardgo/integration/jwt/service/LoginServiceTest.java
  src/test/java/com/boardgo/integration/jwt/service/TokenServiceTest.java
Labels: feat

#240 Feat: 약관동의 목록 조회
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/config/SecurityConfig.java
  src/main/java/com/boardgo/domain/mapper/TermsConditionsMapper.java
  src/main/java/com/boardgo/domain/termsconditions/controller/TermsConditionsController.java
  src/main/java/com/boardgo/domain/termsconditions/controller/UserTermsConditionsController.java
  src/main/java/com/boardgo/domain/termsconditions/service/TermsConditionsQueryServiceV1.java
  src/main/java/com/boardgo/domain/termsconditions/service/TermsConditionsQueryUseCase.java
  src/main/java/com/boardgo/domain/termsconditions/service/facade/UserTermsConditionsCommandFacadeImpl.java
  src/main/java/com/boardgo/domain/termsconditions/service/response/TermsConditionsResponse.java
  src/test/java/com/boardgo/integration/termsconditions/controller/TermsConditionsRestDocs.java
  src/test/java/com/boardgo/integration/termsconditions/controller/UserTermsConditionsRestDocs.java
  src/test/java/com/boardgo/integration/termsconditions/service/TermsConditionsQueryServiceV1Test.java
Labels: feat

#244 Refactor: USER 도메인 facade pattern 리팩토링
  src/main/java/com/boardgo/domain/user/controller/PersonalInfoController.java
  src/main/java/com/boardgo/domain/user/controller/SignupController.java
  src/main/java/com/boardgo/domain/user/controller/TokenController.java
  src/main/java/com/boardgo/domain/user/controller/UserController.java
  src/main/java/com/boardgo/domain/user/service/UserCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserCommandUseCase.java
  src/main/java/com/boardgo/domain/user/service/UserPrTagCommandServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserPrTagCommandUseCase.java
  src/main/java/com/boardgo/domain/user/service/UserQueryServiceV1.java
  src/main/java/com/boardgo/domain/user/service/UserQueryUseCase.java
  src/main/java/com/boardgo/domain/user/service/facade/UserCommandFacade.java
  src/main/java/com/boardgo/domain/user/service/facade/UserCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/termsconditions/service/TermsConditionsQueryServiceV1Test.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/facade/UserCommandFacadeTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserPrTagCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/user/service/UserQueryServiceV1Test.java
Labels: refectoring

#243 Fix: 모임 수정 로직 변경
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/meeting/service/MeetingCommandFacadeImplTest.java
Labels: fix

#245 Fix: 회원가입 시 약관동의 저장
  src/docs/asciidoc/index.adoc
  src/main/java/com/boardgo/domain/meeting/service/facade/MeetingQueryFacadeImpl.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryUseCase.java
  src/main/java/com/boardgo/domain/user/controller/TokenController.java
  src/main/java/com/boardgo/domain/user/controller/request/SignupRequest.java
  src/main/java/com/boardgo/domain/user/controller/request/SocialSignupRequest.java
  src/main/java/com/boardgo/domain/user/service/facade/UserCommandFacadeImpl.java
  src/test/java/com/boardgo/integration/user/controller/SignupDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/TokenDocsTest.java
  src/test/java/com/boardgo/integration/user/controller/UserDocsTest.java
  src/test/java/com/boardgo/integration/user/facade/UserCommandFacadeTest.java
  src/test/java/com/boardgo/integration/user/service/UserCommandServiceV1Test.java
  src/test/java/com/boardgo/integration/validation/ListInStringNotEmptyValidatorTest.java
  src/test/java/com/boardgo/unittest/user/UserInfoEntityTest.java
Labels: fix

#248 Fix: 리뷰 평균평점 중복메소드 수정 및 평가태그 엔티티 복합인덱스 생성
  src/main/java/com/boardgo/domain/review/entity/EvaluationTagEntity.java
  src/main/java/com/boardgo/domain/review/service/ReviewQueryServiceV1.java
  src/test/java/com/boardgo/integration/user/facade/UserCommandFacadeTest.java
Labels: fix

#249 Feat: notification 알림 도메인 엔티티 설계
  src/main/java/com/boardgo/common/exception/NotificationException.java
  src/main/java/com/boardgo/common/exception/advice/dto/ErrorCode.java
  src/main/java/com/boardgo/domain/review/entity/ReviewEntity.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoEntity.java
  src/main/java/com/boardgo/domain/user/entity/UserInfoStatus.java
  src/main/java/com/boardgo/init/TermsConditionsInitializer.java
  src/main/java/com/boardgo/notification/entity/MessageType.java
  src/main/java/com/boardgo/notification/entity/Notification.java
  src/main/java/com/boardgo/notification/entity/NotificationFail.java
  src/main/java/com/boardgo/notification/entity/NotificationMessage.java
  src/main/java/com/boardgo/notification/entity/NotificationMessageFormat.java
  src/main/java/com/boardgo/notification/entity/NotificationType.java
Labels: feat
